[general]
live_config_reload = true

# https://github.com/alacritty/alacritty-theme
# https://github.com/alacritty/alacritty-theme/blob/master/themes/one_dark.toml
[colors]
transparent_background_colors = true

[[colors.indexed_colors]]
color = "0xd19a66"
index = 16

[[colors.indexed_colors]]
color = "0xbe5046"
index = 17

[[colors.indexed_colors]]
color = "0x353b45"
index = 18

[[colors.indexed_colors]]
color = "0x3e4451"
index = 19

[[colors.indexed_colors]]
color = "0x565c64"
index = 20

[[colors.indexed_colors]]
color = "0xb6bdca"
index = 21

# [colors.bright]
# black = "0x545862"
# blue = "0x61afef"
# cyan = "0x56b6c2"
# green = "0x98c379"
# magenta = "0xc678dd"
# red = "0xe06c75"
# white = "0xc8ccd4"
# yellow = "0xe5c07b"

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'

[colors.cursor]
cursor = "0xabb2bf"
text = "0x282c34"

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# [colors.normal]
# black = "0x282c34"
# blue = "0x61afef"
# cyan = "0x56b6c2"
# green = "0x98c379"
# magenta = "0xc678dd"
# red = "0xe06c75"
# white = "0xabb2bf"
# yellow = "0xe5c07b"

[colors.primary]
background = '#282c34'
foreground = '#abb2bf'
# [colors.primary]
# background = "0x282c34"
# foreground = "0xabb2bf"

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.offset]
x = 0
y = 2

[scrolling]
history = 100000

[terminal.shell]
args = ["--login"]
program = "zsh"

[window]
decorations = "none"
dynamic_padding = true
opacity = 1.00
startup_mode = "Fullscreen"

[window.padding]
x = 0
y = 0

[mouse]# If this is `true`, the cursor is temporarily hidden when typing.
hide_when_typing = true
